# Exploratory Data Analysis (EDA)

Este notebook explora la data limpia para encontrar patrones, distribuciones y relaciones.

Objetivos principales:
- Entender la distribución de las puntuaciones de ansiedad
- Analizar diferencias demográficas
- Explorar relaciones entre síntomas
- Obtener información útil para futuros modelos

### Setup del proyecto

In [9]:
# Setup project root
import sys
from pathlib import Path

project_root = Path().resolve().parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

# Asegura que src esté en sys.path
src_path = project_root / "src"
if str(src_path) not in sys.path:
    sys.path.append(str(src_path))

### Imports

In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from src.config import DATA_PROCESSED, OUTPUTS_FIGURES
from src.data_loader import load_excel

sns.set(style="whitegrid")

### Cargar data limpia

In [11]:
df = load_excel(DATA_PROCESSED)
df.head()

,id,age,category,date,gender,totalScore,BAI_1,BAI_2,BAI_3,BAI_4,...,BAI_12,BAI_13,BAI_14,BAI_15,BAI_16,BAI_17,BAI_18,BAI_19,BAI_20,BAI_21
0,024ccc066e5f36803f8861b9ee3d94888e5370faed41a9...,24,LOW,"July 22, 2025 at 12:45:35 PM UTC-6",M,11,1,2,0,0,...,0,0,0,0,0,1,0,0,0,2
1,02f2a803fa9512cbee77681b62aec389336d01bf56e54b...,19,LOW,"July 23, 2025 at 9:17:01 AM UTC-6",M,15,2,3,0,2,...,0,0,0,1,0,0,1,0,0,2
2,044a25cf19eab34fffd83bdd006ce8338150351ac18ebf...,23,LOW,"July 22, 2025 at 12:49:46 PM UTC-6",M,16,2,2,0,2,...,0,0,1,0,0,2,0,0,0,1
3,05590f956566724748711d0b68f1b44f3fabfc87cab7cf...,25,LOW,"July 22, 2025 at 12:40:20 PM UTC-6",M,4,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
4,0ba67bab767aadf47f4be2743015846e30a32459939c76...,23,LOW,"July 22, 2025 at 1:18:40 PM UTC-6",M,10,0,1,0,2,...,0,0,0,0,1,0,1,0,0,0

### Overview

In [12]:
df.shape
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 27 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          114 non-null    str
 1   age         114 non-null    int64
 2   category    114 non-null    str
 3   date        114 non-null    str
 4   gender      114 non-null    str
 5   totalScore  114 non-null    int64
 6   BAI_1       114 non-null    int64
 7   BAI_2       114 non-null    int64
 8   BAI_3       114 non-null    int64
 9   BAI_4       114 non-null    int64
 10  BAI_5       114 non-null    int64
 11  BAI_6       114 non-null    int64
 12  BAI_7       114 non-null    int64
 13  BAI_8       114 non-null    int64
 14  BAI_9       114 non-null    int64
 15  BAI_10      114 non-null    int64
 16  BAI_11      114 non-null    int64
 17  BAI_12      114 non-null    int64
 18  BAI_13      114 non-null    int64
 19  BAI_14      114 non-null    int64
 20  BAI_15      114 non-null    int64
 21  BAI_16      114 non-null    int64
 22  BAI_17      114 non-null    int64
 23  BAI_18      114 non-null    int64
 24  BAI_19      114 non-null    int64
 25  BAI_20      114 non-null    int64
 26  BAI_21      114 non-null    int64
dtypes: int64(23), str(4)
memory usage: 24.2 KB

,age,totalScore,BAI_1,BAI_2,BAI_3,BAI_4,BAI_5,BAI_6,BAI_7,BAI_8,...,BAI_12,BAI_13,BAI_14,BAI_15,BAI_16,BAI_17,BAI_18,BAI_19,BAI_20,BAI_21
count,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,...,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000,114.000000
mean,23.385965,18.745614,0.991228,1.456140,0.622807,1.543860,1.517544,0.666667,1.000000,0.929825,...,0.640351,0.570175,0.956140,0.517544,0.692982,0.745614,1.052632,0.447368,0.684211,0.921053
std,3.898057,10.929226,0.867257,0.932599,0.845502,0.996812,1.106957,0.869001,0.940721,0.947463,...,0.893707,0.808903,0.962945,0.755305,0.903554,0.860247,0.985219,0.692464,0.855133,0.987934
min,17.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,21.000000,11.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,23.000000,16.500000,1.000000,2.000000,0.000000,2.000000,2.000000,0.000000,1.000000,1.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000
75%,25.000000,26.000000,2.000000,2.000000,1.000000,2.000000,2.000000,1.000000,2.000000,2.000000,...,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,2.000000
max,42.000000,61.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,...,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000